version: 1.0.{build}
image: Visual Studio 2017

install:
- cmd: choco install dotnet.script

build_script:
- cmd: >-
    cd build

    refreshenv

    dotnet script build.csx

artifacts:
- path: /**/*.nupkg
  name: NuGet Packages

test: off
environment:
    IS_SECURE_BUILDENVIRONMENT:
        secure: xYC5jpSucUdHr8YwfxWefw==
    GITHUB_REPO_TOKEN:
        secure: FSPXTPuTgFMaZA7DubJoX217SkWhFLN2BGqCCi4gBux967eFtwkhbrafm7ay8cP2
    NUGET_APIKEY:
        secure: ynFcRQX0oim3DdR5Y8s4BtynS/NYRG059GvWGckqhpZGNZVvhvvn5UUWgsyPKLKm